version: 1

language: python 3.10

build:
  - python -m venv venv
  - . venv/bin/activate
  - pip install -r requirements.txt 

test:
  - echo "No tests in this example."

run:
  - . venv/bin/activate
  - chmod +x dark
  - python3 dark.py
