# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PDARK

#on:
#  push:
  #  branches: [ $default-branch ]
 # pull_request:
  #  branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m venv venv
        . venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        apt-get update && apt-get install -y gcc libpthread-stubs0-dev
        pip install telebot flask pymongo aiohttp python-telegram-bot pytz
        git clone https://github.com/okoleleonline1/Dark.git
        cd Dark
        chmod +x dark
    - name: Test with pytest
      run: |
        nohup python3 dark.py
